name: Continuous Integration
on: [push, pull_request]
jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cleanup
        run: sed -i "s/%NAME%/test/g" build.sc
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: openjdk@1.14
      - name: Cache Scala
        uses: coursier/cache-action@v5
      - name: SBT Test
        run: sbt test
